import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, breadcrumbJsonLd } from "@/components/breadcrumbs";
import { JsonLd } from "@/components/json-ld";
import { StudyRows } from "@/components/resource-lists";
import { getVideoBySlug } from "@/lib/content-repository";

type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const video = await getVideoBySlug(slug); return video ? { title: video.seoTitle || video.title, description: video.seoDescription || video.description, alternates: { canonical: `/videok/${slug}` } } : {}; }
export default async function VideoPage({ params }: Props) { const { slug } = await params; const video = await getVideoBySlug(slug); if (!video) notFound(); const crumbs = [{ label: "Kezdőlap", href: "/" }, { label: "Videók", href: "/videok" }, { label: video.title, href: `/videok/${video.slug}` }]; return <div className="page-shell"><JsonLd data={breadcrumbJsonLd(crumbs)} /><Breadcrumbs items={[...crumbs.slice(0, -1), { label: video.title }]} /><div className="detail-grid"><article className="detail-copy"><p className="eyebrow">Videóajánló</p><h1>{video.title}</h1><p className="lead">{video.description}</p><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${video.youtubeId}`} title={video.title} allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin" /></div><p><a className="text-link" href={video.youtubeUrl} target="_blank" rel="noopener noreferrer">Megnézem a YouTube-on</a></p></article><aside className="detail-sidebar"><div className="detail-sidebar__section"><h2>Témák</h2><ul>{video.topics.map((topic) => <li key={topic.id}><Link className="text-link" href={`/temak/${topic.slug}`}>{topic.title}</Link></li>)}</ul></div>{video.channelName ? <div className="detail-sidebar__section"><h2>Csatorna</h2><ul><li>{video.channelName}</li></ul></div> : null}</aside></div>{video.relatedStudies.length ? <section className="section"><div className="section-heading"><div><p className="eyebrow">Együtt ajánljuk</p><h2>Kapcsolódó tanulmányok</h2></div></div><StudyRows studies={video.relatedStudies} /></section> : null}</div>; }
